
package com.yu.webservice.cxf.wsimport;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "LanguageServicePortType", targetNamespace = "http://cxf.webservice.yu.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface LanguageServicePortType {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "http://cxf.webservice.yu.com/")
    @RequestWrapper(localName = "getLanguage", targetNamespace = "http://cxf.webservice.yu.com/", className = "com.yu.webservice.cxf.wsimport.GetLanguage")
    @ResponseWrapper(localName = "getLanguageResponse", targetNamespace = "http://cxf.webservice.yu.com/", className = "com.yu.webservice.cxf.wsimport.GetLanguageResponse")
    public String getLanguage(
        @WebParam(name = "arg0", targetNamespace = "http://cxf.webservice.yu.com/")
        int arg0);

}
