
package com.yu.webservice.cxf.wsimport;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "LanguageService", targetNamespace = "http://cxf.webservice.yu.com/", wsdlLocation = "http://127.0.0.1:8888/ws/cxf/languangeService?WSDL")
public class LanguageService
    extends Service
{

    private final static URL LANGUAGESERVICE_WSDL_LOCATION;
    private final static WebServiceException LANGUAGESERVICE_EXCEPTION;
    private final static QName LANGUAGESERVICE_QNAME = new QName("http://cxf.webservice.yu.com/", "LanguageService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:8888/ws/cxf/languangeService?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        LANGUAGESERVICE_WSDL_LOCATION = url;
        LANGUAGESERVICE_EXCEPTION = e;
    }

    public LanguageService() {
        super(__getWsdlLocation(), LANGUAGESERVICE_QNAME);
    }

    public LanguageService(WebServiceFeature... features) {
        super(__getWsdlLocation(), LANGUAGESERVICE_QNAME, features);
    }

    public LanguageService(URL wsdlLocation) {
        super(wsdlLocation, LANGUAGESERVICE_QNAME);
    }

    public LanguageService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, LANGUAGESERVICE_QNAME, features);
    }

    public LanguageService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LanguageService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns LanguageServicePortType
     */
    @WebEndpoint(name = "LanguageServicePort")
    public LanguageServicePortType getLanguageServicePort() {
        return super.getPort(new QName("http://cxf.webservice.yu.com/", "LanguageServicePort"), LanguageServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LanguageServicePortType
     */
    @WebEndpoint(name = "LanguageServicePort")
    public LanguageServicePortType getLanguageServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://cxf.webservice.yu.com/", "LanguageServicePort"), LanguageServicePortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (LANGUAGESERVICE_EXCEPTION!= null) {
            throw LANGUAGESERVICE_EXCEPTION;
        }
        return LANGUAGESERVICE_WSDL_LOCATION;
    }

}
