package com.yino.drudgery.mapper;

import com.yino.drudgery.po.JobBasicInfo;
import com.yino.drudgery.po.JobBasicInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface JobBasicInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_basic_info
     *
     * @mbggenerated Mon Apr 17 17:17:05 CST 2017
     */
    int countByExample(JobBasicInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_basic_info
     *
     * @mbggenerated Mon Apr 17 17:17:05 CST 2017
     */
    int deleteByExample(JobBasicInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_basic_info
     *
     * @mbggenerated Mon Apr 17 17:17:05 CST 2017
     */
    int deleteByPrimaryKey(String jobBasicUid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_basic_info
     *
     * @mbggenerated Mon Apr 17 17:17:05 CST 2017
     */
    int insert(JobBasicInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_basic_info
     *
     * @mbggenerated Mon Apr 17 17:17:05 CST 2017
     */
    int insertSelective(JobBasicInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_basic_info
     *
     * @mbggenerated Mon Apr 17 17:17:05 CST 2017
     */
    List<JobBasicInfo> selectByExample(JobBasicInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_basic_info
     *
     * @mbggenerated Mon Apr 17 17:17:05 CST 2017
     */
    JobBasicInfo selectByPrimaryKey(String jobBasicUid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_basic_info
     *
     * @mbggenerated Mon Apr 17 17:17:05 CST 2017
     */
    int updateByExampleSelective(@Param("record") JobBasicInfo record, @Param("example") JobBasicInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_basic_info
     *
     * @mbggenerated Mon Apr 17 17:17:05 CST 2017
     */
    int updateByExample(@Param("record") JobBasicInfo record, @Param("example") JobBasicInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_basic_info
     *
     * @mbggenerated Mon Apr 17 17:17:05 CST 2017
     */
    int updateByPrimaryKeySelective(JobBasicInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_basic_info
     *
     * @mbggenerated Mon Apr 17 17:17:05 CST 2017
     */
    int updateByPrimaryKey(JobBasicInfo record);
}