package com.yino.drudgery.mapper;

import com.yino.drudgery.po.JobParamInfo;
import com.yino.drudgery.po.JobParamInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface JobParamInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_param_info
     *
     * @mbggenerated Mon Apr 17 17:17:05 CST 2017
     */
    int countByExample(JobParamInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_param_info
     *
     * @mbggenerated Mon Apr 17 17:17:05 CST 2017
     */
    int deleteByExample(JobParamInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_param_info
     *
     * @mbggenerated Mon Apr 17 17:17:05 CST 2017
     */
    int deleteByPrimaryKey(String jobParamUid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_param_info
     *
     * @mbggenerated Mon Apr 17 17:17:05 CST 2017
     */
    int insert(JobParamInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_param_info
     *
     * @mbggenerated Mon Apr 17 17:17:05 CST 2017
     */
    int insertSelective(JobParamInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_param_info
     *
     * @mbggenerated Mon Apr 17 17:17:05 CST 2017
     */
    List<JobParamInfo> selectByExample(JobParamInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_param_info
     *
     * @mbggenerated Mon Apr 17 17:17:05 CST 2017
     */
    JobParamInfo selectByPrimaryKey(String jobParamUid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_param_info
     *
     * @mbggenerated Mon Apr 17 17:17:05 CST 2017
     */
    int updateByExampleSelective(@Param("record") JobParamInfo record, @Param("example") JobParamInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_param_info
     *
     * @mbggenerated Mon Apr 17 17:17:05 CST 2017
     */
    int updateByExample(@Param("record") JobParamInfo record, @Param("example") JobParamInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_param_info
     *
     * @mbggenerated Mon Apr 17 17:17:05 CST 2017
     */
    int updateByPrimaryKeySelective(JobParamInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_param_info
     *
     * @mbggenerated Mon Apr 17 17:17:05 CST 2017
     */
    int updateByPrimaryKey(JobParamInfo record);
}