package com.yino.drudgery.po;

import java.io.Serializable;
import java.util.Date;

public class JobBasicInfo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_basic_info.job_basic_uid
     *
     * @mbggenerated Mon Apr 17 17:17:05 CST 2017
     */
    private String jobBasicUid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_basic_info.row_status
     *
     * @mbggenerated Mon Apr 17 17:17:05 CST 2017
     */
    private Byte rowStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_basic_info.row_version
     *
     * @mbggenerated Mon Apr 17 17:17:05 CST 2017
     */
    private Date rowVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_basic_info.job_type
     *
     * @mbggenerated Mon Apr 17 17:17:05 CST 2017
     */
    private Byte jobType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_basic_info.job_group
     *
     * @mbggenerated Mon Apr 17 17:17:05 CST 2017
     */
    private String jobGroup;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_basic_info.is_parallel_exe
     *
     * @mbggenerated Mon Apr 17 17:17:05 CST 2017
     */
    private Byte isParallelExe;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_basic_info.is_enable
     *
     * @mbggenerated Mon Apr 17 17:17:05 CST 2017
     */
    private Byte isEnable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_basic_info.trigger_type
     *
     * @mbggenerated Mon Apr 17 17:17:05 CST 2017
     */
    private Byte triggerType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_basic_info.trigger_param
     *
     * @mbggenerated Mon Apr 17 17:17:05 CST 2017
     */
    private String triggerParam;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_basic_info.priority
     *
     * @mbggenerated Mon Apr 17 17:17:05 CST 2017
     */
    private Byte priority;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_basic_info.job_status
     *
     * @mbggenerated Mon Apr 17 17:17:05 CST 2017
     */
    private Byte jobStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_basic_info.update_time
     *
     * @mbggenerated Mon Apr 17 17:17:05 CST 2017
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_basic_info.job_name
     *
     * @mbggenerated Mon Apr 17 17:17:05 CST 2017
     */
    private String jobName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table job_basic_info
     *
     * @mbggenerated Mon Apr 17 17:17:05 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_basic_info.job_basic_uid
     *
     * @return the value of job_basic_info.job_basic_uid
     *
     * @mbggenerated Mon Apr 17 17:17:05 CST 2017
     */
    public String getJobBasicUid() {
        return jobBasicUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_basic_info.job_basic_uid
     *
     * @param jobBasicUid the value for job_basic_info.job_basic_uid
     *
     * @mbggenerated Mon Apr 17 17:17:05 CST 2017
     */
    public void setJobBasicUid(String jobBasicUid) {
        this.jobBasicUid = jobBasicUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_basic_info.row_status
     *
     * @return the value of job_basic_info.row_status
     *
     * @mbggenerated Mon Apr 17 17:17:05 CST 2017
     */
    public Byte getRowStatus() {
        return rowStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_basic_info.row_status
     *
     * @param rowStatus the value for job_basic_info.row_status
     *
     * @mbggenerated Mon Apr 17 17:17:05 CST 2017
     */
    public void setRowStatus(Byte rowStatus) {
        this.rowStatus = rowStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_basic_info.row_version
     *
     * @return the value of job_basic_info.row_version
     *
     * @mbggenerated Mon Apr 17 17:17:05 CST 2017
     */
    public Date getRowVersion() {
        return rowVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_basic_info.row_version
     *
     * @param rowVersion the value for job_basic_info.row_version
     *
     * @mbggenerated Mon Apr 17 17:17:05 CST 2017
     */
    public void setRowVersion(Date rowVersion) {
        this.rowVersion = rowVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_basic_info.job_type
     *
     * @return the value of job_basic_info.job_type
     *
     * @mbggenerated Mon Apr 17 17:17:05 CST 2017
     */
    public Byte getJobType() {
        return jobType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_basic_info.job_type
     *
     * @param jobType the value for job_basic_info.job_type
     *
     * @mbggenerated Mon Apr 17 17:17:05 CST 2017
     */
    public void setJobType(Byte jobType) {
        this.jobType = jobType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_basic_info.job_group
     *
     * @return the value of job_basic_info.job_group
     *
     * @mbggenerated Mon Apr 17 17:17:05 CST 2017
     */
    public String getJobGroup() {
        return jobGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_basic_info.job_group
     *
     * @param jobGroup the value for job_basic_info.job_group
     *
     * @mbggenerated Mon Apr 17 17:17:05 CST 2017
     */
    public void setJobGroup(String jobGroup) {
        this.jobGroup = jobGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_basic_info.is_parallel_exe
     *
     * @return the value of job_basic_info.is_parallel_exe
     *
     * @mbggenerated Mon Apr 17 17:17:05 CST 2017
     */
    public Byte getIsParallelExe() {
        return isParallelExe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_basic_info.is_parallel_exe
     *
     * @param isParallelExe the value for job_basic_info.is_parallel_exe
     *
     * @mbggenerated Mon Apr 17 17:17:05 CST 2017
     */
    public void setIsParallelExe(Byte isParallelExe) {
        this.isParallelExe = isParallelExe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_basic_info.is_enable
     *
     * @return the value of job_basic_info.is_enable
     *
     * @mbggenerated Mon Apr 17 17:17:05 CST 2017
     */
    public Byte getIsEnable() {
        return isEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_basic_info.is_enable
     *
     * @param isEnable the value for job_basic_info.is_enable
     *
     * @mbggenerated Mon Apr 17 17:17:05 CST 2017
     */
    public void setIsEnable(Byte isEnable) {
        this.isEnable = isEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_basic_info.trigger_type
     *
     * @return the value of job_basic_info.trigger_type
     *
     * @mbggenerated Mon Apr 17 17:17:05 CST 2017
     */
    public Byte getTriggerType() {
        return triggerType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_basic_info.trigger_type
     *
     * @param triggerType the value for job_basic_info.trigger_type
     *
     * @mbggenerated Mon Apr 17 17:17:05 CST 2017
     */
    public void setTriggerType(Byte triggerType) {
        this.triggerType = triggerType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_basic_info.trigger_param
     *
     * @return the value of job_basic_info.trigger_param
     *
     * @mbggenerated Mon Apr 17 17:17:05 CST 2017
     */
    public String getTriggerParam() {
        return triggerParam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_basic_info.trigger_param
     *
     * @param triggerParam the value for job_basic_info.trigger_param
     *
     * @mbggenerated Mon Apr 17 17:17:05 CST 2017
     */
    public void setTriggerParam(String triggerParam) {
        this.triggerParam = triggerParam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_basic_info.priority
     *
     * @return the value of job_basic_info.priority
     *
     * @mbggenerated Mon Apr 17 17:17:05 CST 2017
     */
    public Byte getPriority() {
        return priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_basic_info.priority
     *
     * @param priority the value for job_basic_info.priority
     *
     * @mbggenerated Mon Apr 17 17:17:05 CST 2017
     */
    public void setPriority(Byte priority) {
        this.priority = priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_basic_info.job_status
     *
     * @return the value of job_basic_info.job_status
     *
     * @mbggenerated Mon Apr 17 17:17:05 CST 2017
     */
    public Byte getJobStatus() {
        return jobStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_basic_info.job_status
     *
     * @param jobStatus the value for job_basic_info.job_status
     *
     * @mbggenerated Mon Apr 17 17:17:05 CST 2017
     */
    public void setJobStatus(Byte jobStatus) {
        this.jobStatus = jobStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_basic_info.update_time
     *
     * @return the value of job_basic_info.update_time
     *
     * @mbggenerated Mon Apr 17 17:17:05 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_basic_info.update_time
     *
     * @param updateTime the value for job_basic_info.update_time
     *
     * @mbggenerated Mon Apr 17 17:17:05 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_basic_info.job_name
     *
     * @return the value of job_basic_info.job_name
     *
     * @mbggenerated Mon Apr 17 17:17:05 CST 2017
     */
    public String getJobName() {
        return jobName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_basic_info.job_name
     *
     * @param jobName the value for job_basic_info.job_name
     *
     * @mbggenerated Mon Apr 17 17:17:05 CST 2017
     */
    public void setJobName(String jobName) {
        this.jobName = jobName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_basic_info
     *
     * @mbggenerated Mon Apr 17 17:17:05 CST 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        JobBasicInfo other = (JobBasicInfo) that;
        return (this.getJobBasicUid() == null ? other.getJobBasicUid() == null : this.getJobBasicUid().equals(other.getJobBasicUid()))
            && (this.getRowStatus() == null ? other.getRowStatus() == null : this.getRowStatus().equals(other.getRowStatus()))
            && (this.getRowVersion() == null ? other.getRowVersion() == null : this.getRowVersion().equals(other.getRowVersion()))
            && (this.getJobType() == null ? other.getJobType() == null : this.getJobType().equals(other.getJobType()))
            && (this.getJobGroup() == null ? other.getJobGroup() == null : this.getJobGroup().equals(other.getJobGroup()))
            && (this.getIsParallelExe() == null ? other.getIsParallelExe() == null : this.getIsParallelExe().equals(other.getIsParallelExe()))
            && (this.getIsEnable() == null ? other.getIsEnable() == null : this.getIsEnable().equals(other.getIsEnable()))
            && (this.getTriggerType() == null ? other.getTriggerType() == null : this.getTriggerType().equals(other.getTriggerType()))
            && (this.getTriggerParam() == null ? other.getTriggerParam() == null : this.getTriggerParam().equals(other.getTriggerParam()))
            && (this.getPriority() == null ? other.getPriority() == null : this.getPriority().equals(other.getPriority()))
            && (this.getJobStatus() == null ? other.getJobStatus() == null : this.getJobStatus().equals(other.getJobStatus()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getJobName() == null ? other.getJobName() == null : this.getJobName().equals(other.getJobName()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_basic_info
     *
     * @mbggenerated Mon Apr 17 17:17:05 CST 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getJobBasicUid() == null) ? 0 : getJobBasicUid().hashCode());
        result = prime * result + ((getRowStatus() == null) ? 0 : getRowStatus().hashCode());
        result = prime * result + ((getRowVersion() == null) ? 0 : getRowVersion().hashCode());
        result = prime * result + ((getJobType() == null) ? 0 : getJobType().hashCode());
        result = prime * result + ((getJobGroup() == null) ? 0 : getJobGroup().hashCode());
        result = prime * result + ((getIsParallelExe() == null) ? 0 : getIsParallelExe().hashCode());
        result = prime * result + ((getIsEnable() == null) ? 0 : getIsEnable().hashCode());
        result = prime * result + ((getTriggerType() == null) ? 0 : getTriggerType().hashCode());
        result = prime * result + ((getTriggerParam() == null) ? 0 : getTriggerParam().hashCode());
        result = prime * result + ((getPriority() == null) ? 0 : getPriority().hashCode());
        result = prime * result + ((getJobStatus() == null) ? 0 : getJobStatus().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getJobName() == null) ? 0 : getJobName().hashCode());
        return result;
    }
}