package com.yino.drudgery.po;

import java.io.Serializable;
import java.util.Date;

public class JobLog implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_log.job_log_uid
     *
     * @mbggenerated Mon Apr 17 17:17:05 CST 2017
     */
    private String jobLogUid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_log.row_status
     *
     * @mbggenerated Mon Apr 17 17:17:05 CST 2017
     */
    private Byte rowStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_log.row_version
     *
     * @mbggenerated Mon Apr 17 17:17:05 CST 2017
     */
    private Date rowVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_log.log_type
     *
     * @mbggenerated Mon Apr 17 17:17:05 CST 2017
     */
    private Byte logType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_log.msg
     *
     * @mbggenerated Mon Apr 17 17:17:05 CST 2017
     */
    private String msg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_log.run_period
     *
     * @mbggenerated Mon Apr 17 17:17:05 CST 2017
     */
    private Integer runPeriod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_log.update_time
     *
     * @mbggenerated Mon Apr 17 17:17:05 CST 2017
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_log.job_basic_uid
     *
     * @mbggenerated Mon Apr 17 17:17:05 CST 2017
     */
    private String jobBasicUid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table job_log
     *
     * @mbggenerated Mon Apr 17 17:17:05 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_log.job_log_uid
     *
     * @return the value of job_log.job_log_uid
     *
     * @mbggenerated Mon Apr 17 17:17:05 CST 2017
     */
    public String getJobLogUid() {
        return jobLogUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_log.job_log_uid
     *
     * @param jobLogUid the value for job_log.job_log_uid
     *
     * @mbggenerated Mon Apr 17 17:17:05 CST 2017
     */
    public void setJobLogUid(String jobLogUid) {
        this.jobLogUid = jobLogUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_log.row_status
     *
     * @return the value of job_log.row_status
     *
     * @mbggenerated Mon Apr 17 17:17:05 CST 2017
     */
    public Byte getRowStatus() {
        return rowStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_log.row_status
     *
     * @param rowStatus the value for job_log.row_status
     *
     * @mbggenerated Mon Apr 17 17:17:05 CST 2017
     */
    public void setRowStatus(Byte rowStatus) {
        this.rowStatus = rowStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_log.row_version
     *
     * @return the value of job_log.row_version
     *
     * @mbggenerated Mon Apr 17 17:17:05 CST 2017
     */
    public Date getRowVersion() {
        return rowVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_log.row_version
     *
     * @param rowVersion the value for job_log.row_version
     *
     * @mbggenerated Mon Apr 17 17:17:05 CST 2017
     */
    public void setRowVersion(Date rowVersion) {
        this.rowVersion = rowVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_log.log_type
     *
     * @return the value of job_log.log_type
     *
     * @mbggenerated Mon Apr 17 17:17:05 CST 2017
     */
    public Byte getLogType() {
        return logType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_log.log_type
     *
     * @param logType the value for job_log.log_type
     *
     * @mbggenerated Mon Apr 17 17:17:05 CST 2017
     */
    public void setLogType(Byte logType) {
        this.logType = logType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_log.msg
     *
     * @return the value of job_log.msg
     *
     * @mbggenerated Mon Apr 17 17:17:05 CST 2017
     */
    public String getMsg() {
        return msg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_log.msg
     *
     * @param msg the value for job_log.msg
     *
     * @mbggenerated Mon Apr 17 17:17:05 CST 2017
     */
    public void setMsg(String msg) {
        this.msg = msg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_log.run_period
     *
     * @return the value of job_log.run_period
     *
     * @mbggenerated Mon Apr 17 17:17:05 CST 2017
     */
    public Integer getRunPeriod() {
        return runPeriod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_log.run_period
     *
     * @param runPeriod the value for job_log.run_period
     *
     * @mbggenerated Mon Apr 17 17:17:05 CST 2017
     */
    public void setRunPeriod(Integer runPeriod) {
        this.runPeriod = runPeriod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_log.update_time
     *
     * @return the value of job_log.update_time
     *
     * @mbggenerated Mon Apr 17 17:17:05 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_log.update_time
     *
     * @param updateTime the value for job_log.update_time
     *
     * @mbggenerated Mon Apr 17 17:17:05 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_log.job_basic_uid
     *
     * @return the value of job_log.job_basic_uid
     *
     * @mbggenerated Mon Apr 17 17:17:05 CST 2017
     */
    public String getJobBasicUid() {
        return jobBasicUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_log.job_basic_uid
     *
     * @param jobBasicUid the value for job_log.job_basic_uid
     *
     * @mbggenerated Mon Apr 17 17:17:05 CST 2017
     */
    public void setJobBasicUid(String jobBasicUid) {
        this.jobBasicUid = jobBasicUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_log
     *
     * @mbggenerated Mon Apr 17 17:17:05 CST 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        JobLog other = (JobLog) that;
        return (this.getJobLogUid() == null ? other.getJobLogUid() == null : this.getJobLogUid().equals(other.getJobLogUid()))
            && (this.getRowStatus() == null ? other.getRowStatus() == null : this.getRowStatus().equals(other.getRowStatus()))
            && (this.getRowVersion() == null ? other.getRowVersion() == null : this.getRowVersion().equals(other.getRowVersion()))
            && (this.getLogType() == null ? other.getLogType() == null : this.getLogType().equals(other.getLogType()))
            && (this.getMsg() == null ? other.getMsg() == null : this.getMsg().equals(other.getMsg()))
            && (this.getRunPeriod() == null ? other.getRunPeriod() == null : this.getRunPeriod().equals(other.getRunPeriod()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getJobBasicUid() == null ? other.getJobBasicUid() == null : this.getJobBasicUid().equals(other.getJobBasicUid()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_log
     *
     * @mbggenerated Mon Apr 17 17:17:05 CST 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getJobLogUid() == null) ? 0 : getJobLogUid().hashCode());
        result = prime * result + ((getRowStatus() == null) ? 0 : getRowStatus().hashCode());
        result = prime * result + ((getRowVersion() == null) ? 0 : getRowVersion().hashCode());
        result = prime * result + ((getLogType() == null) ? 0 : getLogType().hashCode());
        result = prime * result + ((getMsg() == null) ? 0 : getMsg().hashCode());
        result = prime * result + ((getRunPeriod() == null) ? 0 : getRunPeriod().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getJobBasicUid() == null) ? 0 : getJobBasicUid().hashCode());
        return result;
    }
}