package com.yino.drudgery.po;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class JobLogExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table job_log
     *
     * @mbggenerated Mon Apr 17 17:17:05 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table job_log
     *
     * @mbggenerated Mon Apr 17 17:17:05 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table job_log
     *
     * @mbggenerated Mon Apr 17 17:17:05 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table job_log
     *
     * @mbggenerated Mon Apr 17 17:17:05 CST 2017
     */
    protected Integer limitStart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table job_log
     *
     * @mbggenerated Mon Apr 17 17:17:05 CST 2017
     */
    protected Integer limitEnd;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_log
     *
     * @mbggenerated Mon Apr 17 17:17:05 CST 2017
     */
    public JobLogExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_log
     *
     * @mbggenerated Mon Apr 17 17:17:05 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_log
     *
     * @mbggenerated Mon Apr 17 17:17:05 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_log
     *
     * @mbggenerated Mon Apr 17 17:17:05 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_log
     *
     * @mbggenerated Mon Apr 17 17:17:05 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_log
     *
     * @mbggenerated Mon Apr 17 17:17:05 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_log
     *
     * @mbggenerated Mon Apr 17 17:17:05 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_log
     *
     * @mbggenerated Mon Apr 17 17:17:05 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_log
     *
     * @mbggenerated Mon Apr 17 17:17:05 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_log
     *
     * @mbggenerated Mon Apr 17 17:17:05 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_log
     *
     * @mbggenerated Mon Apr 17 17:17:05 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_log
     *
     * @mbggenerated Mon Apr 17 17:17:05 CST 2017
     */
    public void setLimitStart(Integer limitStart) {
        this.limitStart=limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_log
     *
     * @mbggenerated Mon Apr 17 17:17:05 CST 2017
     */
    public Integer getLimitStart() {
        return limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_log
     *
     * @mbggenerated Mon Apr 17 17:17:05 CST 2017
     */
    public void setLimitEnd(Integer limitEnd) {
        this.limitEnd=limitEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_log
     *
     * @mbggenerated Mon Apr 17 17:17:05 CST 2017
     */
    public Integer getLimitEnd() {
        return limitEnd;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table job_log
     *
     * @mbggenerated Mon Apr 17 17:17:05 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andJobLogUidIsNull() {
            addCriterion("job_log_uid is null");
            return (Criteria) this;
        }

        public Criteria andJobLogUidIsNotNull() {
            addCriterion("job_log_uid is not null");
            return (Criteria) this;
        }

        public Criteria andJobLogUidEqualTo(String value) {
            addCriterion("job_log_uid =", value, "jobLogUid");
            return (Criteria) this;
        }

        public Criteria andJobLogUidNotEqualTo(String value) {
            addCriterion("job_log_uid <>", value, "jobLogUid");
            return (Criteria) this;
        }

        public Criteria andJobLogUidGreaterThan(String value) {
            addCriterion("job_log_uid >", value, "jobLogUid");
            return (Criteria) this;
        }

        public Criteria andJobLogUidGreaterThanOrEqualTo(String value) {
            addCriterion("job_log_uid >=", value, "jobLogUid");
            return (Criteria) this;
        }

        public Criteria andJobLogUidLessThan(String value) {
            addCriterion("job_log_uid <", value, "jobLogUid");
            return (Criteria) this;
        }

        public Criteria andJobLogUidLessThanOrEqualTo(String value) {
            addCriterion("job_log_uid <=", value, "jobLogUid");
            return (Criteria) this;
        }

        public Criteria andJobLogUidLike(String value) {
            addCriterion("job_log_uid like", value, "jobLogUid");
            return (Criteria) this;
        }

        public Criteria andJobLogUidNotLike(String value) {
            addCriterion("job_log_uid not like", value, "jobLogUid");
            return (Criteria) this;
        }

        public Criteria andJobLogUidIn(List<String> values) {
            addCriterion("job_log_uid in", values, "jobLogUid");
            return (Criteria) this;
        }

        public Criteria andJobLogUidNotIn(List<String> values) {
            addCriterion("job_log_uid not in", values, "jobLogUid");
            return (Criteria) this;
        }

        public Criteria andJobLogUidBetween(String value1, String value2) {
            addCriterion("job_log_uid between", value1, value2, "jobLogUid");
            return (Criteria) this;
        }

        public Criteria andJobLogUidNotBetween(String value1, String value2) {
            addCriterion("job_log_uid not between", value1, value2, "jobLogUid");
            return (Criteria) this;
        }

        public Criteria andRowStatusIsNull() {
            addCriterion("row_status is null");
            return (Criteria) this;
        }

        public Criteria andRowStatusIsNotNull() {
            addCriterion("row_status is not null");
            return (Criteria) this;
        }

        public Criteria andRowStatusEqualTo(Byte value) {
            addCriterion("row_status =", value, "rowStatus");
            return (Criteria) this;
        }

        public Criteria andRowStatusNotEqualTo(Byte value) {
            addCriterion("row_status <>", value, "rowStatus");
            return (Criteria) this;
        }

        public Criteria andRowStatusGreaterThan(Byte value) {
            addCriterion("row_status >", value, "rowStatus");
            return (Criteria) this;
        }

        public Criteria andRowStatusGreaterThanOrEqualTo(Byte value) {
            addCriterion("row_status >=", value, "rowStatus");
            return (Criteria) this;
        }

        public Criteria andRowStatusLessThan(Byte value) {
            addCriterion("row_status <", value, "rowStatus");
            return (Criteria) this;
        }

        public Criteria andRowStatusLessThanOrEqualTo(Byte value) {
            addCriterion("row_status <=", value, "rowStatus");
            return (Criteria) this;
        }

        public Criteria andRowStatusIn(List<Byte> values) {
            addCriterion("row_status in", values, "rowStatus");
            return (Criteria) this;
        }

        public Criteria andRowStatusNotIn(List<Byte> values) {
            addCriterion("row_status not in", values, "rowStatus");
            return (Criteria) this;
        }

        public Criteria andRowStatusBetween(Byte value1, Byte value2) {
            addCriterion("row_status between", value1, value2, "rowStatus");
            return (Criteria) this;
        }

        public Criteria andRowStatusNotBetween(Byte value1, Byte value2) {
            addCriterion("row_status not between", value1, value2, "rowStatus");
            return (Criteria) this;
        }

        public Criteria andRowVersionIsNull() {
            addCriterion("row_version is null");
            return (Criteria) this;
        }

        public Criteria andRowVersionIsNotNull() {
            addCriterion("row_version is not null");
            return (Criteria) this;
        }

        public Criteria andRowVersionEqualTo(Date value) {
            addCriterion("row_version =", value, "rowVersion");
            return (Criteria) this;
        }

        public Criteria andRowVersionNotEqualTo(Date value) {
            addCriterion("row_version <>", value, "rowVersion");
            return (Criteria) this;
        }

        public Criteria andRowVersionGreaterThan(Date value) {
            addCriterion("row_version >", value, "rowVersion");
            return (Criteria) this;
        }

        public Criteria andRowVersionGreaterThanOrEqualTo(Date value) {
            addCriterion("row_version >=", value, "rowVersion");
            return (Criteria) this;
        }

        public Criteria andRowVersionLessThan(Date value) {
            addCriterion("row_version <", value, "rowVersion");
            return (Criteria) this;
        }

        public Criteria andRowVersionLessThanOrEqualTo(Date value) {
            addCriterion("row_version <=", value, "rowVersion");
            return (Criteria) this;
        }

        public Criteria andRowVersionIn(List<Date> values) {
            addCriterion("row_version in", values, "rowVersion");
            return (Criteria) this;
        }

        public Criteria andRowVersionNotIn(List<Date> values) {
            addCriterion("row_version not in", values, "rowVersion");
            return (Criteria) this;
        }

        public Criteria andRowVersionBetween(Date value1, Date value2) {
            addCriterion("row_version between", value1, value2, "rowVersion");
            return (Criteria) this;
        }

        public Criteria andRowVersionNotBetween(Date value1, Date value2) {
            addCriterion("row_version not between", value1, value2, "rowVersion");
            return (Criteria) this;
        }

        public Criteria andLogTypeIsNull() {
            addCriterion("log_type is null");
            return (Criteria) this;
        }

        public Criteria andLogTypeIsNotNull() {
            addCriterion("log_type is not null");
            return (Criteria) this;
        }

        public Criteria andLogTypeEqualTo(Byte value) {
            addCriterion("log_type =", value, "logType");
            return (Criteria) this;
        }

        public Criteria andLogTypeNotEqualTo(Byte value) {
            addCriterion("log_type <>", value, "logType");
            return (Criteria) this;
        }

        public Criteria andLogTypeGreaterThan(Byte value) {
            addCriterion("log_type >", value, "logType");
            return (Criteria) this;
        }

        public Criteria andLogTypeGreaterThanOrEqualTo(Byte value) {
            addCriterion("log_type >=", value, "logType");
            return (Criteria) this;
        }

        public Criteria andLogTypeLessThan(Byte value) {
            addCriterion("log_type <", value, "logType");
            return (Criteria) this;
        }

        public Criteria andLogTypeLessThanOrEqualTo(Byte value) {
            addCriterion("log_type <=", value, "logType");
            return (Criteria) this;
        }

        public Criteria andLogTypeIn(List<Byte> values) {
            addCriterion("log_type in", values, "logType");
            return (Criteria) this;
        }

        public Criteria andLogTypeNotIn(List<Byte> values) {
            addCriterion("log_type not in", values, "logType");
            return (Criteria) this;
        }

        public Criteria andLogTypeBetween(Byte value1, Byte value2) {
            addCriterion("log_type between", value1, value2, "logType");
            return (Criteria) this;
        }

        public Criteria andLogTypeNotBetween(Byte value1, Byte value2) {
            addCriterion("log_type not between", value1, value2, "logType");
            return (Criteria) this;
        }

        public Criteria andMsgIsNull() {
            addCriterion("msg is null");
            return (Criteria) this;
        }

        public Criteria andMsgIsNotNull() {
            addCriterion("msg is not null");
            return (Criteria) this;
        }

        public Criteria andMsgEqualTo(String value) {
            addCriterion("msg =", value, "msg");
            return (Criteria) this;
        }

        public Criteria andMsgNotEqualTo(String value) {
            addCriterion("msg <>", value, "msg");
            return (Criteria) this;
        }

        public Criteria andMsgGreaterThan(String value) {
            addCriterion("msg >", value, "msg");
            return (Criteria) this;
        }

        public Criteria andMsgGreaterThanOrEqualTo(String value) {
            addCriterion("msg >=", value, "msg");
            return (Criteria) this;
        }

        public Criteria andMsgLessThan(String value) {
            addCriterion("msg <", value, "msg");
            return (Criteria) this;
        }

        public Criteria andMsgLessThanOrEqualTo(String value) {
            addCriterion("msg <=", value, "msg");
            return (Criteria) this;
        }

        public Criteria andMsgLike(String value) {
            addCriterion("msg like", value, "msg");
            return (Criteria) this;
        }

        public Criteria andMsgNotLike(String value) {
            addCriterion("msg not like", value, "msg");
            return (Criteria) this;
        }

        public Criteria andMsgIn(List<String> values) {
            addCriterion("msg in", values, "msg");
            return (Criteria) this;
        }

        public Criteria andMsgNotIn(List<String> values) {
            addCriterion("msg not in", values, "msg");
            return (Criteria) this;
        }

        public Criteria andMsgBetween(String value1, String value2) {
            addCriterion("msg between", value1, value2, "msg");
            return (Criteria) this;
        }

        public Criteria andMsgNotBetween(String value1, String value2) {
            addCriterion("msg not between", value1, value2, "msg");
            return (Criteria) this;
        }

        public Criteria andRunPeriodIsNull() {
            addCriterion("run_period is null");
            return (Criteria) this;
        }

        public Criteria andRunPeriodIsNotNull() {
            addCriterion("run_period is not null");
            return (Criteria) this;
        }

        public Criteria andRunPeriodEqualTo(Integer value) {
            addCriterion("run_period =", value, "runPeriod");
            return (Criteria) this;
        }

        public Criteria andRunPeriodNotEqualTo(Integer value) {
            addCriterion("run_period <>", value, "runPeriod");
            return (Criteria) this;
        }

        public Criteria andRunPeriodGreaterThan(Integer value) {
            addCriterion("run_period >", value, "runPeriod");
            return (Criteria) this;
        }

        public Criteria andRunPeriodGreaterThanOrEqualTo(Integer value) {
            addCriterion("run_period >=", value, "runPeriod");
            return (Criteria) this;
        }

        public Criteria andRunPeriodLessThan(Integer value) {
            addCriterion("run_period <", value, "runPeriod");
            return (Criteria) this;
        }

        public Criteria andRunPeriodLessThanOrEqualTo(Integer value) {
            addCriterion("run_period <=", value, "runPeriod");
            return (Criteria) this;
        }

        public Criteria andRunPeriodIn(List<Integer> values) {
            addCriterion("run_period in", values, "runPeriod");
            return (Criteria) this;
        }

        public Criteria andRunPeriodNotIn(List<Integer> values) {
            addCriterion("run_period not in", values, "runPeriod");
            return (Criteria) this;
        }

        public Criteria andRunPeriodBetween(Integer value1, Integer value2) {
            addCriterion("run_period between", value1, value2, "runPeriod");
            return (Criteria) this;
        }

        public Criteria andRunPeriodNotBetween(Integer value1, Integer value2) {
            addCriterion("run_period not between", value1, value2, "runPeriod");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andJobBasicUidIsNull() {
            addCriterion("job_basic_uid is null");
            return (Criteria) this;
        }

        public Criteria andJobBasicUidIsNotNull() {
            addCriterion("job_basic_uid is not null");
            return (Criteria) this;
        }

        public Criteria andJobBasicUidEqualTo(String value) {
            addCriterion("job_basic_uid =", value, "jobBasicUid");
            return (Criteria) this;
        }

        public Criteria andJobBasicUidNotEqualTo(String value) {
            addCriterion("job_basic_uid <>", value, "jobBasicUid");
            return (Criteria) this;
        }

        public Criteria andJobBasicUidGreaterThan(String value) {
            addCriterion("job_basic_uid >", value, "jobBasicUid");
            return (Criteria) this;
        }

        public Criteria andJobBasicUidGreaterThanOrEqualTo(String value) {
            addCriterion("job_basic_uid >=", value, "jobBasicUid");
            return (Criteria) this;
        }

        public Criteria andJobBasicUidLessThan(String value) {
            addCriterion("job_basic_uid <", value, "jobBasicUid");
            return (Criteria) this;
        }

        public Criteria andJobBasicUidLessThanOrEqualTo(String value) {
            addCriterion("job_basic_uid <=", value, "jobBasicUid");
            return (Criteria) this;
        }

        public Criteria andJobBasicUidLike(String value) {
            addCriterion("job_basic_uid like", value, "jobBasicUid");
            return (Criteria) this;
        }

        public Criteria andJobBasicUidNotLike(String value) {
            addCriterion("job_basic_uid not like", value, "jobBasicUid");
            return (Criteria) this;
        }

        public Criteria andJobBasicUidIn(List<String> values) {
            addCriterion("job_basic_uid in", values, "jobBasicUid");
            return (Criteria) this;
        }

        public Criteria andJobBasicUidNotIn(List<String> values) {
            addCriterion("job_basic_uid not in", values, "jobBasicUid");
            return (Criteria) this;
        }

        public Criteria andJobBasicUidBetween(String value1, String value2) {
            addCriterion("job_basic_uid between", value1, value2, "jobBasicUid");
            return (Criteria) this;
        }

        public Criteria andJobBasicUidNotBetween(String value1, String value2) {
            addCriterion("job_basic_uid not between", value1, value2, "jobBasicUid");
            return (Criteria) this;
        }

        public Criteria andJobLogUidLikeInsensitive(String value) {
            addCriterion("upper(job_log_uid) like", value.toUpperCase(), "jobLogUid");
            return (Criteria) this;
        }

        public Criteria andMsgLikeInsensitive(String value) {
            addCriterion("upper(msg) like", value.toUpperCase(), "msg");
            return (Criteria) this;
        }

        public Criteria andJobBasicUidLikeInsensitive(String value) {
            addCriterion("upper(job_basic_uid) like", value.toUpperCase(), "jobBasicUid");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table job_log
     *
     * @mbggenerated do_not_delete_during_merge Mon Apr 17 17:17:05 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table job_log
     *
     * @mbggenerated Mon Apr 17 17:17:05 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}