package com.yino.drudgery.po;

import java.io.Serializable;
import java.util.Date;

public class JobParamInfo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_param_info.job_param_uid
     *
     * @mbggenerated Mon Apr 17 17:17:05 CST 2017
     */
    private String jobParamUid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_param_info.row_status
     *
     * @mbggenerated Mon Apr 17 17:17:05 CST 2017
     */
    private Byte rowStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_param_info.row_version
     *
     * @mbggenerated Mon Apr 17 17:17:05 CST 2017
     */
    private Date rowVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_param_info.param_type
     *
     * @mbggenerated Mon Apr 17 17:17:05 CST 2017
     */
    private String paramType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_param_info.param_key
     *
     * @mbggenerated Mon Apr 17 17:17:05 CST 2017
     */
    private String paramKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_param_info.param_value
     *
     * @mbggenerated Mon Apr 17 17:17:05 CST 2017
     */
    private String paramValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_param_info.update_time
     *
     * @mbggenerated Mon Apr 17 17:17:05 CST 2017
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_param_info.job_basic_uid
     *
     * @mbggenerated Mon Apr 17 17:17:05 CST 2017
     */
    private String jobBasicUid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table job_param_info
     *
     * @mbggenerated Mon Apr 17 17:17:05 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_param_info.job_param_uid
     *
     * @return the value of job_param_info.job_param_uid
     *
     * @mbggenerated Mon Apr 17 17:17:05 CST 2017
     */
    public String getJobParamUid() {
        return jobParamUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_param_info.job_param_uid
     *
     * @param jobParamUid the value for job_param_info.job_param_uid
     *
     * @mbggenerated Mon Apr 17 17:17:05 CST 2017
     */
    public void setJobParamUid(String jobParamUid) {
        this.jobParamUid = jobParamUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_param_info.row_status
     *
     * @return the value of job_param_info.row_status
     *
     * @mbggenerated Mon Apr 17 17:17:05 CST 2017
     */
    public Byte getRowStatus() {
        return rowStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_param_info.row_status
     *
     * @param rowStatus the value for job_param_info.row_status
     *
     * @mbggenerated Mon Apr 17 17:17:05 CST 2017
     */
    public void setRowStatus(Byte rowStatus) {
        this.rowStatus = rowStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_param_info.row_version
     *
     * @return the value of job_param_info.row_version
     *
     * @mbggenerated Mon Apr 17 17:17:05 CST 2017
     */
    public Date getRowVersion() {
        return rowVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_param_info.row_version
     *
     * @param rowVersion the value for job_param_info.row_version
     *
     * @mbggenerated Mon Apr 17 17:17:05 CST 2017
     */
    public void setRowVersion(Date rowVersion) {
        this.rowVersion = rowVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_param_info.param_type
     *
     * @return the value of job_param_info.param_type
     *
     * @mbggenerated Mon Apr 17 17:17:05 CST 2017
     */
    public String getParamType() {
        return paramType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_param_info.param_type
     *
     * @param paramType the value for job_param_info.param_type
     *
     * @mbggenerated Mon Apr 17 17:17:05 CST 2017
     */
    public void setParamType(String paramType) {
        this.paramType = paramType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_param_info.param_key
     *
     * @return the value of job_param_info.param_key
     *
     * @mbggenerated Mon Apr 17 17:17:05 CST 2017
     */
    public String getParamKey() {
        return paramKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_param_info.param_key
     *
     * @param paramKey the value for job_param_info.param_key
     *
     * @mbggenerated Mon Apr 17 17:17:05 CST 2017
     */
    public void setParamKey(String paramKey) {
        this.paramKey = paramKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_param_info.param_value
     *
     * @return the value of job_param_info.param_value
     *
     * @mbggenerated Mon Apr 17 17:17:05 CST 2017
     */
    public String getParamValue() {
        return paramValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_param_info.param_value
     *
     * @param paramValue the value for job_param_info.param_value
     *
     * @mbggenerated Mon Apr 17 17:17:05 CST 2017
     */
    public void setParamValue(String paramValue) {
        this.paramValue = paramValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_param_info.update_time
     *
     * @return the value of job_param_info.update_time
     *
     * @mbggenerated Mon Apr 17 17:17:05 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_param_info.update_time
     *
     * @param updateTime the value for job_param_info.update_time
     *
     * @mbggenerated Mon Apr 17 17:17:05 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_param_info.job_basic_uid
     *
     * @return the value of job_param_info.job_basic_uid
     *
     * @mbggenerated Mon Apr 17 17:17:05 CST 2017
     */
    public String getJobBasicUid() {
        return jobBasicUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_param_info.job_basic_uid
     *
     * @param jobBasicUid the value for job_param_info.job_basic_uid
     *
     * @mbggenerated Mon Apr 17 17:17:05 CST 2017
     */
    public void setJobBasicUid(String jobBasicUid) {
        this.jobBasicUid = jobBasicUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_param_info
     *
     * @mbggenerated Mon Apr 17 17:17:05 CST 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        JobParamInfo other = (JobParamInfo) that;
        return (this.getJobParamUid() == null ? other.getJobParamUid() == null : this.getJobParamUid().equals(other.getJobParamUid()))
            && (this.getRowStatus() == null ? other.getRowStatus() == null : this.getRowStatus().equals(other.getRowStatus()))
            && (this.getRowVersion() == null ? other.getRowVersion() == null : this.getRowVersion().equals(other.getRowVersion()))
            && (this.getParamType() == null ? other.getParamType() == null : this.getParamType().equals(other.getParamType()))
            && (this.getParamKey() == null ? other.getParamKey() == null : this.getParamKey().equals(other.getParamKey()))
            && (this.getParamValue() == null ? other.getParamValue() == null : this.getParamValue().equals(other.getParamValue()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getJobBasicUid() == null ? other.getJobBasicUid() == null : this.getJobBasicUid().equals(other.getJobBasicUid()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_param_info
     *
     * @mbggenerated Mon Apr 17 17:17:05 CST 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getJobParamUid() == null) ? 0 : getJobParamUid().hashCode());
        result = prime * result + ((getRowStatus() == null) ? 0 : getRowStatus().hashCode());
        result = prime * result + ((getRowVersion() == null) ? 0 : getRowVersion().hashCode());
        result = prime * result + ((getParamType() == null) ? 0 : getParamType().hashCode());
        result = prime * result + ((getParamKey() == null) ? 0 : getParamKey().hashCode());
        result = prime * result + ((getParamValue() == null) ? 0 : getParamValue().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getJobBasicUid() == null) ? 0 : getJobBasicUid().hashCode());
        return result;
    }
}