
package com.yu.webservice.endpoint.mywsimport;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PhoneManager", targetNamespace = "http://WebXml.com.cn/", wsdlLocation = "http://127.0.0.1:8888/ws/phoneService?WSDL")
public class PhoneManager
    extends Service
{

    private final static URL PHONEMANAGER_WSDL_LOCATION;
    private final static WebServiceException PHONEMANAGER_EXCEPTION;
    private final static QName PHONEMANAGER_QNAME = new QName("http://WebXml.com.cn/", "PhoneManager");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:8888/ws/phoneService?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PHONEMANAGER_WSDL_LOCATION = url;
        PHONEMANAGER_EXCEPTION = e;
    }

    public PhoneManager() {
        super(__getWsdlLocation(), PHONEMANAGER_QNAME);
    }

    public PhoneManager(WebServiceFeature... features) {
        super(__getWsdlLocation(), PHONEMANAGER_QNAME, features);
    }

    public PhoneManager(URL wsdlLocation) {
        super(wsdlLocation, PHONEMANAGER_QNAME);
    }

    public PhoneManager(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PHONEMANAGER_QNAME, features);
    }

    public PhoneManager(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PhoneManager(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PhoneService
     */
    @WebEndpoint(name = "PhoneServicePort")
    public PhoneService getPhoneServicePort() {
        return super.getPort(new QName("http://WebXml.com.cn/", "PhoneServicePort"), PhoneService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PhoneService
     */
    @WebEndpoint(name = "PhoneServicePort")
    public PhoneService getPhoneServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://WebXml.com.cn/", "PhoneServicePort"), PhoneService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PHONEMANAGER_EXCEPTION!= null) {
            throw PHONEMANAGER_EXCEPTION;
        }
        return PHONEMANAGER_WSDL_LOCATION;
    }

}
